@startuml   
class Customer {
    - userId: int
    - name: String
    - testCustomer: String
}
class PaymentCard {
    - cardNumber: String
    - expirationDate: Date
    - testPaymentCard: String
}
Customer "1" --> "0..3" PaymentCard
@enduml